export const MD_COMPONENTS = {
  h1:     ({ children }) => <h1 className="text-2xl font-bold mt-6 mb-3">{children}</h1>,
  h2:     ({ children }) => <h2 className="text-xl font-bold mt-5 mb-2 border-b pb-1">{children}</h2>,
  h3:     ({ children }) => <h3 className="text-lg font-semibold mt-4 mb-2">{children}</h3>,
  h4:     ({ children }) => <h4 className="text-base font-semibold mt-3 mb-1">{children}</h4>,
  p:      ({ children }) => <p className="mb-3 leading-relaxed">{children}</p>,
  ul:     ({ children }) => <ul className="list-disc list-inside mb-3 space-y-1">{children}</ul>,
  ol:     ({ children }) => <ol className="list-decimal list-inside mb-3 space-y-1">{children}</ol>,
  li:     ({ children }) => <li className="ml-4">{children}</li>,
  table:  ({ children }) => <div className="max-w-full overflow-x-auto mb-4" tabIndex={0} role="region" aria-label="表（横にスクロールできます）"><table className="w-full border-collapse">{children}</table></div>,
  th:     ({ children }) => <th className="min-w-32 align-top border border-gray-300 bg-gray-100 px-3 py-2 text-left text-sm font-semibold">{children}</th>,
  td:     ({ children }) => <td className="min-w-32 align-top border border-gray-300 px-3 py-2 text-sm">{children}</td>,
  strong: ({ children }) => <strong className="font-bold">{children}</strong>,
  pre:    ({ children }) => <pre className="max-w-full overflow-x-auto mb-4">{children}</pre>,
  code:   ({ children }) => <code className="bg-gray-100 px-1 rounded text-sm">{children}</code>,
}
